/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Controller;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import views.*;
import java.sql.*;

/**
 *
 * @author TSIARO
 */
public class FinalPage extends javax.swing.JFrame {

    /**
     * Creates new form FinalPage
     */
    public FinalPage() {
        initComponents();
        this.setSize(1080,720);
        
        //Initialisation des composants
        
        ImageIcon ii=new ImageIcon(getClass().getResource("/views/Logo.png"));
        Image img=(ii).getImage().getScaledInstance(logo.getWidth(), logo.getHeight(), Image.SCALE_SMOOTH);
        ii=new ImageIcon(img);
        logo.setIcon(ii);
        this.setIconImage(img);
        this.setTitle("DigitalDistrict");
        this.setLocationRelativeTo(null);
        
        
        //Initialisation de la frame interne
        
        
        contenu.setLayout(new BorderLayout());
        contenu.add(new views.WelcomePanel(),BorderLayout.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     * @throws SQLException 
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        contenu = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        nouveau = new javax.swing.JPanel();
        lnouveau = new javax.swing.JLabel();
        ancien = new javax.swing.JPanel();
        lancien = new javax.swing.JLabel();
        liste = new javax.swing.JPanel();
        lliste = new javax.swing.JLabel();
        historique = new javax.swing.JPanel();
        lhistorique = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        autorisation = new javax.swing.JPanel();
        lautorisation = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 0));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Controller/republique2.png"))); // NOI18N

        contenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0), 3));

        javax.swing.GroupLayout contenuLayout = new javax.swing.GroupLayout(contenu);
        contenu.setLayout(contenuLayout);
        contenuLayout.setHorizontalGroup(
            contenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        contenuLayout.setVerticalGroup(
            contenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(0, 51, 0));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 0), 3, true));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FARITRA: "+Model.Quariter.Faritra());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 148, 9, 155);
        jPanel2.add(jLabel1, gridBagConstraints);

        jPanel4.setBackground(new java.awt.Color(0, 51, 0));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 0), 3, true));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("FOKONTANY: "+Model.Quariter.Fokontany());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 89, 9, 98);
        jPanel4.add(jLabel3, gridBagConstraints);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/ISPM.png"))); // NOI18N

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("(c)copyright 2023");

        jPanel5.setBackground(new java.awt.Color(0, 51, 0));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 0), 2, true), "ASA", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 204, 0))); // NOI18N

        nouveau.setBackground(new java.awt.Color(0, 51, 0));
        nouveau.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0)));
        nouveau.setForeground(new java.awt.Color(255, 255, 0));
        nouveau.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                nouveauMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                nouveauMouseMoved(evt);
            }
        });
        nouveau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nouveauMouseClicked(evt);
            }
        });

        lnouveau.setBackground(new java.awt.Color(0, 51, 0));
        lnouveau.setForeground(new java.awt.Color(255, 204, 0));
        lnouveau.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lnouveau.setText("MPONINA VAOVAO");
        lnouveau.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lnouveauMouseDragged(evt);
            }
        });
        lnouveau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lnouveauMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout nouveauLayout = new javax.swing.GroupLayout(nouveau);
        nouveau.setLayout(nouveauLayout);
        nouveauLayout.setHorizontalGroup(
            nouveauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nouveauLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lnouveau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        nouveauLayout.setVerticalGroup(
            nouveauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nouveauLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lnouveau)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ancien.setBackground(new java.awt.Color(0, 51, 0));
        ancien.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0)));
        ancien.setForeground(new java.awt.Color(255, 255, 0));

        lancien.setBackground(new java.awt.Color(0, 51, 0));
        lancien.setForeground(new java.awt.Color(255, 204, 0));
        lancien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lancien.setText("ANTOTAN'ISA");
        lancien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lancienMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ancienLayout = new javax.swing.GroupLayout(ancien);
        ancien.setLayout(ancienLayout);
        ancienLayout.setHorizontalGroup(
            ancienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ancienLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lancien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ancienLayout.setVerticalGroup(
            ancienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ancienLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lancien)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        liste.setBackground(new java.awt.Color(0, 51, 0));
        liste.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0)));
        liste.setForeground(new java.awt.Color(255, 255, 0));

        lliste.setBackground(new java.awt.Color(0, 51, 0));
        lliste.setForeground(new java.awt.Color(255, 204, 0));
        lliste.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lliste.setText("LISITRA");
        lliste.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                llisteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout listeLayout = new javax.swing.GroupLayout(liste);
        liste.setLayout(listeLayout);
        listeLayout.setHorizontalGroup(
            listeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lliste, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        listeLayout.setVerticalGroup(
            listeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lliste)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        historique.setBackground(new java.awt.Color(0, 51, 0));
        historique.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0)));
        historique.setForeground(new java.awt.Color(255, 255, 0));

        lhistorique.setBackground(new java.awt.Color(0, 51, 0));
        lhistorique.setForeground(new java.awt.Color(255, 204, 0));
        lhistorique.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lhistorique.setText("FANARAHA-MASO");
        lhistorique.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lhistoriqueMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout historiqueLayout = new javax.swing.GroupLayout(historique);
        historique.setLayout(historiqueLayout);
        historiqueLayout.setHorizontalGroup(
            historiqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(historiqueLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lhistorique, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        historiqueLayout.setVerticalGroup(
            historiqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(historiqueLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lhistorique)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/Logo.png"))); // NOI18N
        logo.setText("jLabel6");
        logo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0), 2));
        logo.setPreferredSize(new java.awt.Dimension(1145, 1004));
        logo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoMouseClicked(evt);
            }
        });

        autorisation.setBackground(new java.awt.Color(0, 51, 0));
        autorisation.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0)));
        autorisation.setForeground(new java.awt.Color(255, 255, 0));

        lautorisation.setBackground(new java.awt.Color(0, 51, 0));
        lautorisation.setForeground(new java.awt.Color(255, 204, 0));
        lautorisation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lautorisation.setText("FAHAZOAN-DALANA");
        lautorisation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lautorisationMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout autorisationLayout = new javax.swing.GroupLayout(autorisation);
        autorisation.setLayout(autorisationLayout);
        autorisationLayout.setHorizontalGroup(
            autorisationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(autorisationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lautorisation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        autorisationLayout.setVerticalGroup(
            autorisationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(autorisationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lautorisation)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nouveau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ancien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(liste, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(historique, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
            .addComponent(autorisation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(nouveau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ancien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(liste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(historique, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(autorisation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel2))
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5))
                            .addComponent(contenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(contenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lnouveauMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lnouveauMouseDragged
        
    }//GEN-LAST:event_lnouveauMouseDragged

    private void nouveauMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nouveauMouseDragged
        nouveau.setBackground(new java.awt.Color(255, 255, 0));
    }//GEN-LAST:event_nouveauMouseDragged

    private void nouveauMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nouveauMouseMoved
        
        
    }//GEN-LAST:event_nouveauMouseMoved

    private void nouveauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nouveauMouseClicked
        
    }//GEN-LAST:event_nouveauMouseClicked

    private void lnouveauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lnouveauMouseClicked
        nouveau.setBorder(javax.swing.BorderFactory.createLineBorder(Color.WHITE));
        ancien.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0)));
        liste.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0)));
        historique.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0)));
        autorisation.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0)));
        
        lnouveau.setForeground(Color.WHITE);
        lancien.setForeground(new java.awt.Color(255, 255, 0));
        lliste.setForeground(new java.awt.Color(255, 255, 0));
        lhistorique.setForeground(new java.awt.Color(255, 255, 0));
        lautorisation.setForeground(new java.awt.Color(255, 255, 0));
        
        contenu.removeAll();
        contenu.add(new views.Inscription(),BorderLayout.CENTER);
        this.setVisible(true);
    }//GEN-LAST:event_lnouveauMouseClicked

    private void lancienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lancienMouseClicked
        ancien.setBorder(javax.swing.BorderFactory.createLineBorder(Color.WHITE));
        nouveau.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0)));
        liste.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0)));
        historique.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0)));
        autorisation.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0)));
        
        
        lancien.setForeground(Color.WHITE);
        lnouveau.setForeground(new java.awt.Color(255, 255, 0));
        lliste.setForeground(new java.awt.Color(255, 255, 0));
        lhistorique.setForeground(new java.awt.Color(255, 255, 0));
        lautorisation.setForeground(new java.awt.Color(255, 255, 0));
        
        contenu.removeAll();
        contenu.add(new views.Statistique(),BorderLayout.CENTER);
        this.setVisible(true);
    }//GEN-LAST:event_lancienMouseClicked

    private void llisteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_llisteMouseClicked
        liste.setBorder(javax.swing.BorderFactory.createLineBorder(Color.WHITE));
        nouveau.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0)));
        ancien.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0)));
        historique.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0)));
        
        
        lliste.setForeground(Color.WHITE);
        lnouveau.setForeground(new java.awt.Color(255, 255, 0));
        lancien.setForeground(new java.awt.Color(255, 255, 0));
        lhistorique.setForeground(new java.awt.Color(255, 255, 0));
        lautorisation.setForeground(new java.awt.Color(255, 255, 0));
        
        contenu.removeAll();
        contenu.add(new views.Liste(),BorderLayout.CENTER);
        this.setVisible(true);
    }//GEN-LAST:event_llisteMouseClicked

    private void lhistoriqueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lhistoriqueMouseClicked
        historique.setBorder(javax.swing.BorderFactory.createLineBorder(Color.WHITE));
        nouveau.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0)));
        liste.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0)));
        ancien.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0)));
        autorisation.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0)));
        
        
        lhistorique.setForeground(Color.WHITE);
        lnouveau.setForeground(new java.awt.Color(255, 255, 0));
        lliste.setForeground(new java.awt.Color(255, 255, 0));
        lancien.setForeground(new java.awt.Color(255, 255, 0));
        lautorisation.setForeground(new java.awt.Color(255, 255, 0));
        
        contenu.removeAll();
        contenu.add(new views.Historique(),BorderLayout.CENTER);
        this.setVisible(true);
    }//GEN-LAST:event_lhistoriqueMouseClicked

    private void lautorisationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lautorisationMouseClicked
        autorisation.setBorder(javax.swing.BorderFactory.createLineBorder(Color.WHITE));
        nouveau.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0)));
        liste.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0)));
        ancien.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0)));
        historique.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0)));
        
        
        lautorisation.setForeground(Color.WHITE);
        lnouveau.setForeground(new java.awt.Color(255, 255, 0));
        lliste.setForeground(new java.awt.Color(255, 255, 0));
        lancien.setForeground(new java.awt.Color(255, 255, 0));
        lhistorique.setForeground(new java.awt.Color(255, 255, 0));
        
        contenu.removeAll();
        contenu.add(new views.Autorisation(),BorderLayout.CENTER);
        this.setVisible(true);
    }//GEN-LAST:event_lautorisationMouseClicked

    private void logoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoMouseClicked
        contenu.removeAll();
        contenu.add(new views.Apropos(),BorderLayout.CENTER);
        this.setVisible(true);
    }//GEN-LAST:event_logoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FinalPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FinalPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FinalPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FinalPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FinalPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ancien;
    private javax.swing.JPanel autorisation;
    private javax.swing.JPanel contenu;
    private javax.swing.JPanel historique;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lancien;
    private javax.swing.JLabel lautorisation;
    private javax.swing.JLabel lhistorique;
    private javax.swing.JPanel liste;
    private javax.swing.JLabel lliste;
    private javax.swing.JLabel lnouveau;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel nouveau;
    // End of variables declaration//GEN-END:variables
}
